import { findByProps } from "@vendetta/metro";
import { commands } from "@vendetta/metro/common";
import { showToast } from "@vendetta/ui/toasts";

const FLAGGED_WORDS: string[] = [
  'cp',
  'child porn',
  'cheese pizza',
  'loli',
  'shota',
  'jailbait',
  'pedo',
  'pedophile',
  'grooming',
  'groomer',
  'minor',
  'underage',
  'under age',
  '14 years old',
  '15 years old',
  '16 years old',
  '17 years old',
  '12 years old',
  '13 years old',
  '11 years old',
  '10 years old',
  '9 years old',
  '8 years old',
  '7 years old',
  '6 years old',
  '5 years old',
  'kid',
  'kids',
  'child',
  'children',
  'toddler',
  'baby',
  'kindergarten',
  'preschool',
  'primary school',
  'elementary school',
  'middle school',
  'schoolgirl',
  'schoolboy',
  'teen',
  'teens',
  'teenager',
  'teenage',
  'adolescent',
  'young boy',
  'young girl',
  'little boy',
  'little girl',
  'small boy',
  'small girl',
  'infant',
  'newborn',
  'nursery',
  'daycare',
  'babysitter',
  'babysit',
  'playground',
  'sleepover',
  'slumber party',
  'snap me',
  'add me on snap',
  'kik me',
  'add my kik',
  'telegram link',
  'whatsapp me',
  'dm me privately',
  'secret chat',
  'keep this private',
  'dont tell anyone',
  'our little secret',
  'just between us',
  'send me pics',
  'send me photos',
  'show me you',
  'show yourself',
  'take a pic',
  'take a picture',
  'webcam',
  'cam with me',
  'video call privately',
  'meet up',
  'meet irl',
  'come to my house',
  'come over',
  'address please',
  'where do you live',
  'where r u',
  'age play',
  'ageplay',
  'age regression',
  'ddlg',
  'ddlb',
  'mdlg',
  'mdlb',
  'abdl',
  'nsfw minor',
  'teen nsfw',
  'child safety',
  'csa',
  'csam',
  'exploitation',
  'incest',
  'rape',
  'sexual assault',
  'molest',
  'molester',
  'molestation',
  'predator',
  'prey',
  'hunting',
  'hunt kids',
  'favorite age',
  'how old',
  'whats your age',
  'how old r u',
  'ur age',
  'ur so young',
  'ur cute',
  'so cute',
  'innocent',
  'innocence',
  'pure',
  'angel',
  'daddy',
  'mommy',
  'sugar daddy',
  'sugar mommy',
  'sugar baby',
  'pay for pics',
  'buy pics',
  'sell pics',
  'trade pics',
  'trade nudes',
  'send nudes',
  'nude trade',
  'nudes for sale',
  'onlyfans minor',
  'onlyfans teen',
  'patreon minor',
  'discord kitten',
  'kitten',
  'pet play',
  'petplay',
  'master',
  'mistress',
  'slave',
  'obey',
  'obey me',
  'good boy',
  'good girl',
  'bad boy',
  'bad girl',
  'naughty',
  'naughty boy',
  'naughty girl',
  'punish',
  'punishment',
  'spank',
  'spanking',
  'discipline',
  'timeout',
  'grounded',
  'grounding',
  'adult baby',
  'diaper',
  'pacifier',
  'bottle feed',
  'breastfeed',
  'breastfeeding',
  'lactation',
  'pregnant',
  'pregnancy',
  'impregnate',
  'breeding',
  'fertile',
  'virgin',
  'virginity',
  'first time',
  'deflower',
  'cherry pop',
  'popping cherry',
  'corrupt',
  'corrupting',
  'train you',
  'training you',
  'teach you',
  'i will teach',
  'mentor',
  'mentoring',
  'tutor',
  'tutoring',
  'private lesson',
  'private tutor',
  'one on one',
  'alone together',
  'alone with me',
  'alone with you',
  'no parents',
  'parents gone',
  'home alone',
  'house empty',
  'empty house',
  'my parents',
  'your parents',
  'parents asleep',
  'sneak out',
  'sneaking out',
  'run away',
  'runaway',
  'hide',
  'hide this',
  'hide chat',
  'delete messages',
  'clear chat',
  'dont screenshot',
  'no screenshots',
  'disappearing messages',
  'vanish mode',
  'self destruct',
  'burner account',
  'alt account',
  'fake account',
  'fake age',
  'pretend age',
  'lie about age',
  'roleplay age',
  'rp age',
  'age is just',
  'age doesnt matter',
  'age gap',
  'age difference',
  'older man',
  'older woman',
  'younger man',
  'younger woman',
  'big brother',
  'big sister',
  'step brother',
  'step sister',
  'step dad',
  'step mom',
  'step father',
  'step mother',
  'uncle',
  'auntie',
  'cousin',
  'family fun',
  'family secret',
  'wrestling',
  'tickle',
  'tickling',
  'massage',
  'back rub',
  'sleep together',
  'share bed',
  'cuddle',
  'cuddling',
  'snuggle',
  'kiss',
  'kissing',
  'make out',
  'making out',
  'touch you',
  'touch me',
  'feel you',
  'feel me',
  'body',
  'your body',
  'my body',
  'hot body',
  'sexy body',
  'cute body',
  'tight',
  'smooth',
  'soft',
  'hairless',
  'shaved',
  'smooth skin',
  'soft skin',
  'baby skin',
  'young skin',
  'youthful',
  'boyish',
  'girlish',
  'childish',
  'childlike',
  'petite',
  'tiny',
  'small',
  'short',
  'flat chest',
  'no curves',
  'skinny',
  'thin',
  'slim',
  'bony',
  'frail',
  'delicate',
  'fragile',
  'weak',
  'helpless',
  'vulnerable',
  'trust me',
  'trust',
  'i care',
  'i love you',
  'love you',
  'ily',
  'i like you',
  'crush',
  'boyfriend',
  'girlfriend',
  'bf',
  'gf',
  'dating',
  'date me',
  'be mine',
  'belong to me',
  'youre mine',
  'my property',
  'own you',
  'i own you',
  'possession',
  'possess',
  'control',
  'controlling',
  'manipulate',
  'manipulating',
  'gaslight',
  'gaslighting',
  'blackmail',
  'blackmailing',
  'threaten',
  'threatening',
  'dox',
  'doxing',
  'expose',
  'exposing',
  'leak',
  'leaking',
  'ruin you',
  'destroy you',
  'hurt you',
  'harm you',
  'kidnap',
  'kidnapping',
  'abduct',
  'abduction',
  'traffic',
  'trafficking',
  'sell you',
  'buy you',
  'pimp',
  'pimping',
  'prostitute',
  'prostitution',
  'escort',
  'escorting',
  'massage parlor',
  'happy ending',
  'cp link',
  'mega link',
  'drive link',
  'dropbox link',
  'mega nz',
  'mega folder',
  'cp folder',
  'cp server',
  'cp discord',
  'nsfw server',
  'nsfw discord',
  'teen server',
  'teen leak',
  'teen mega',
  'young mega',
  'young leak',
  'preteen',
  'pre teen',
  'tween',
  'tweens',
  'pubescent',
  'puberty',
  'developing',
  'undeveloped',
  'immature',
  'underdeveloped',
  'child model',
  'child modeling',
  'child actor',
  'child pageant',
  'beauty pageant',
  'bikini kid',
  'bikini child',
  'swimsuit kid',
  'swimsuit child',
  'bath time',
  'bathtime',
  'bathroom',
  'shower',
  'changing room',
  'locker room',
  'undress',
  'undressing',
  'dress up',
  'dressing up',
  'costume',
  'cosplay minor',
  'cosplay teen',
  'anime minor',
  'anime loli',
  'anime shota',
  'hentai minor',
  'hentai loli',
  'hentai shota',
  'ero loli',
  'ero shota',
  'furry minor',
  'furry cub',
  'cub art',
  'cub porn',
  'foal',
  'foalcon',
  'kidfucker',
  'childfucker',
  'pedobear',
  'pedo bear',
  'minor attracted',
  'minor attraction',
  'map',
  'minor attracted person',
  'nomap',
  'non offending',
  'nonoffending',
  'virtuous pedophile',
  'child love',
  'child lover',
  'boy love',
  'boy lover',
  'girl love',
  'girl lover',
  'bl',
  'gl',
  'yl',
  'young love',
  'true love',
  'forbidden love',
  'secret love',
  'hidden love',
  'taboo',
  'taboo love',
  'taboo relationship',
  'illegal love',
  'illegal relationship',
  'age of consent',
  'consent age',
  'legal age',
  'barely legal',
  'just turned',
  'just turned 18',
  'fresh 18',
  'freshly 18',
  'newly 18'
];

function chunkArray<T>(arr: T[], size: number): T[][] {
  const chunks: T[][] = [];
  for (let i = 0; i < arr.length; i += size) {
    chunks.push(arr.slice(i, i + size));
  }
  return chunks;
}

const messageApi = findByProps("fetchMessages");

export default {
  onLoad: () => {
    commands.registerCommand({
      name: "sweep",
      displayName: "sweep",
      description: "Scan messages from mentioned users for flagged words.",
      displayDescription: "Scan messages from mentioned users for flagged words.",
      options: [
        {
          name: "users",
          displayName: "users",
          description: "Users to scan",
          displayDescription: "Users to scan",
          required: true,
          type: 6 // USER type
        },
        {
          name: "limit",
          displayName: "limit",
          description: "Number of messages to scan per channel",
          displayDescription: "Number of messages to scan per channel",
          required: false,
          type: 4 // INTEGER type
        }
      ],
      execute: async (args: any[], ctx: any) => {
        const guild = ctx.guild;
        if (!guild) {
          showToast("This command only works in servers.", 1);
          return;
        }

        const userIds: string[] = args[0]?.value ? [args[0].value] : [];
        if (userIds.length === 0) {
          showToast("Please mention at least one user.", 1);
          return;
        }

        const messageLimit: number = args[1]?.value || 100;
        const words = FLAGGED_WORDS;

        let reportLines: string[] = [];
        let totalFound = 0;

        showToast("Scanning messages...", 0);

        const textChannels = guild.channels.filter(
          (c: any) => c.type === 0 || c.type === 5
        );

        for (const userId of userIds) {
          for (const ch of textChannels) {
            try {
              const msgs = await messageApi.fetchMessages(ch.id, { limit: messageLimit });
              const userMsgs = msgs.filter((m: any) => m.author.id === userId);

              for (const m of userMsgs) {
                const content: string = m.content.toLowerCase();
                const foundWord = words.find((w) => content.includes(w.toLowerCase()));
                if (foundWord) {
                  const jumpLink = `https://discord.com/channels/${guild.id}/${ch.id}/${m.id}`;
                  reportLines.push(
                    `<@${userId}> in #${ch.name}: [Jump](${jumpLink}) <- flagged: \`${foundWord}\``
                  );
                  totalFound++;
                }
              }
            } catch (e) {}
          }
        }

        if (reportLines.length === 0) {
          showToast(`No flagged messages found in the last ${messageLimit} messages per channel.`, 0);
          return;
        }

        const chunks = chunkArray(reportLines, 20);
        for (const chunk of chunks) {
          await ctx.channel.send({
            embeds: [
              {
                title: "Flagged Messages Report",
                description: chunk.join("\n"),
                color: 0xff0000,
                footer: { text: `Total results: ${totalFound}` }
              }
            ]
          });
        }
      }
    });
  },
  onUnload: () => {
    commands.unregisterCommand("sweep");
  }
};